// AUTO-GENERATED by scripts/generate-search-data.ts
// Do NOT edit manually — run `npx tsx scripts/generate-search-data.ts` to regenerate.
// Generated at: 2026-05-21T10:02:37.156Z

export const LETTERS_DATA: Array<{
  slug: string
  title: string
  year: number
  summary: string
  concepts: string[]
  companies: string[]
}> = [
  {
    "slug": "1956-partnership-letter",
    "title": "The Partnership Agreement - 1956",
    "year": 1956,
    "summary": "The founding document of Buffett Associates, Ltd. - the partnership agreement signed on May 5, 1956 establishing the terms and investment philosophy that would guide Warren Buffett's investment partnership for the next 13 years.",
    "concepts": [
      "value-investing",
      "margin-of-safety",
      "intrinsic-value"
    ],
    "companies": []
  },
  {
    "slug": "1957-partnership-letter",
    "title": "The First Year - 1957",
    "year": 1957,
    "summary": "Buffett's first annual letter to partnership investors. Markets were relatively flat; the partnership was formed late in the year with starting capital of $105,000. Performance was modest but positive.",
    "concepts": [
      "margin-of-safety",
      "value-investing",
      "intrinsic-value"
    ],
    "companies": []
  },
  {
    "slug": "1958-partnership-letter",
    "title": "The Year of the Recession - 1958",
    "year": 1958,
    "summary": "Markets fell sharply in 1958 amid recession fears. The partnership posted gains while the Dow declined. Buffett introduced the concept of \"Mr. Market\" - the market as a bipolar personality offering daily prices.",
    "concepts": [
      "value-investing",
      "margin-of-safety",
      "compounding"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1959-partnership-letter",
    "title": "The Year of Euphoria - 1959",
    "year": 1959,
    "summary": "A bull market year. The Dow rose sharply. Buffett wrote about the dangers of euphoria and the difficulty of maintaining discipline when prices are rising. The partnership maintained its approach of focusing on fundamentals rather than market trends.",
    "concepts": [
      "intrinsic-value",
      "margin-of-safety",
      "second-level-thinking"
    ],
    "companies": []
  },
  {
    "slug": "1960-partnership-letter",
    "title": "The Year of Contradiction - 1960",
    "year": 1960,
    "summary": "A year when the Dow fell 9.3% but the partnership gained 22.8%. Buffett highlighted the Sanborn Map investment case and discussed plans to merge all partnerships into one entity.",
    "concepts": [
      "value-investing",
      "intrinsic-value",
      "compounding"
    ],
    "companies": []
  },
  {
    "slug": "1961-mid-year-letter",
    "title": "Semi-Annual Letter — July 1961",
    "year": 1961,
    "summary": "Buffett's first semi-annual letter announcing plans to merge all partnerships at yearend. Detailed the new profit-sharing arrangements and introduced provisions for withdrawals, borrowing, and tax adjustments.",
    "concepts": [
      "intrinsic-value",
      "margin-of-safety",
      "compounding"
    ],
    "companies": []
  },
  {
    "slug": "1961-partnership-letter",
    "title": "Our Performance in 1961",
    "year": 1961,
    "summary": "Buffett's 15th year investing and 5th year for the partnership. He provided a detailed analysis of his three investment categories: Generals (undervalued securities), Workouts (event-driven), and Control situations. The partnership achieved 45.9% vs 22.2% Dow in 1961, a 23.7 percentage point advantage.",
    "concepts": [
      "intrinsic-value",
      "margin-of-safety",
      "value-investing",
      "compounding",
      "long-term-investing"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1962-mid-year-letter",
    "title": "Semi-Annual Letter — July 1962",
    "year": 1962,
    "summary": "Mid-1962 report showing the partnership's strong performance during a market decline. Dow fell 21.7% in the first half while the partnership declined only 7.5%, a 14.2 percentage point advantage. Includes reprinted 'And a Prediction' section.",
    "concepts": [
      "market-fluctuations",
      "relative-performance",
      "partnership-structure"
    ],
    "companies": []
  },
  {
    "slug": "1962-partnership-letter",
    "title": "Our Performance in 1962",
    "year": 1962,
    "summary": "Buffett's 1962 annual letter written in January 1963. The partnership gained 13.9% vs the Dow's 7.6% decline, a 21.5 percentage point advantage. He detailed his three investment categories: Generals, Workouts, and Controls, with Dempster Mill as the standout control situation. Harry Bottle was brought in to turn around Dempster, raising its per-share value from $35 to $51.",
    "concepts": [
      "intrinsic-value",
      "margin-of-safety",
      "value-investing",
      "cigar-butts",
      "compounding",
      "workouts",
      "control-situations"
    ],
    "companies": [
      "berkshire-hathaway",
      "dempster-mill"
    ]
  },
  {
    "slug": "1963-mid-year-letter",
    "title": "First Half Performance — July 1963",
    "year": 1963,
    "summary": "Mid-1963 report showing partnership gains of 14% vs the Dow's 10% advance. Discusses Dempster Mill turnaround continuing under Harry Bottle, with per-share value rising from $35.25 (Nov 1961) to $64.81 (Nov 1963). Investment companies comparison table included.",
    "concepts": [
      "general-partnerships",
      "dempster-mill",
      "workouts",
      "investment-companies"
    ],
    "companies": [
      "dempster-mill-manufacturing"
    ]
  },
  {
    "slug": "1963-partnership-letter",
    "title": "Our Performance in 1963",
    "year": 1963,
    "summary": "Buffett's 1963 annual letter written in January 1964. The partnership gained 38.7% vs the Dow's 20.7%, a remarkable 18 percentage point advantage. The letter discusses American Express following the Salad Oil scandal, the Unisuper arbitrage trade, and compares performance against four major investment companies. Dempster Mill's operating assets were sold on a going-concern basis, with Harry Bottle celebrated for extraordinary value creation.",
    "concepts": [
      "intrinsic-value",
      "margin-of-safety",
      "unisuper",
      "american-express",
      "dempster-mill",
      "investment-companies"
    ],
    "companies": [
      "american-express",
      "berkshire-hathaway",
      "dempster-mill-manufacturing"
    ]
  },
  {
    "slug": "1963-special-letter",
    "title": "To My Partners for 1964 — November 1963",
    "year": 1963,
    "summary": "Annual administrative letter sent to partners each November. Enclosed partnership agreement amendments for 1964, commitment letters, and a copy of 'The Ground Rules'. At end of October 1963, the partnership had gained approximately 32% vs the Dow's 18.8%, with Dempster Mill operating assets sold on a going-concern basis.",
    "concepts": [
      "general-partnerships",
      "ground-rules",
      "dempster-mill"
    ],
    "companies": [
      "dempster-mill-manufacturing"
    ]
  },
  {
    "slug": "1964-mid-year-letter",
    "title": "First Half Performance — July 1964",
    "year": 1964,
    "summary": "Mid-1964 report with first-half figures. The Dow advanced from 831.68 to 849.79 (plus 2.2%), with dividends bringing overall return to plus 3.8%. Partnership results reported at plus 8.1% — 4.3 percentage points ahead of the Dow for the first half.",
    "concepts": [
      "general-partnerships",
      "dow-theory"
    ],
    "companies": []
  },
  {
    "slug": "1964-partnership-letter",
    "title": "Our Performance in 1964",
    "year": 1964,
    "summary": "Buffett's 1964 annual letter written in January 1965. Partnership gained 27.8% vs the Dow's 18.7%, a 9.1 percentage point advantage. Discusses the Berkshire Hathaway takeover, the decision to end the partnership at yearend 1969, and the 'Year of Discipline' theme — specifically the importance of selling at the right price. Mentions Disney and American Express as lessons in opportunity cost.",
    "concepts": [
      "intrinsic-value",
      "margin-of-safety",
      "opportunity-cost",
      "cigar-butts",
      "berkshire-hathaway"
    ],
    "companies": [
      "berkshire-hathaway",
      "american-express"
    ]
  },
  {
    "slug": "1965-mid-year-letter",
    "title": "First Half Performance - 1965",
    "year": 1965,
    "summary": "Mid-year letter covering first half 1965. Partnership gained 10.4% vs Dow's 0.8%, a 9.6 percentage point advantage. Discusses the controlling interest in Berkshire Hathaway acquisition — a 'General Private Owner' situation where assets and earning power become the dominant factors in value. Mentions the firm's constant goal of a 10 percentage point per annum advantage over the Dow.",
    "concepts": [
      "berkshire-hathaway",
      "control-situations",
      "general-private-owner"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1965-special-letter",
    "title": "Commitment Letter for 1966",
    "year": 1965,
    "summary": "November commitment letter to partners outlining 1966 partnership terms. Introduces Ground Rule 7 reflecting a moderate shift in Buffett's attitude over time. Describes valuation methodology for Berkshire Hathaway controlling interest — halfway between net current asset value and book value, effectively valuing current assets at 100 cents on the dollar and fixed assets at 50 cents.",
    "concepts": [
      "ground-rules",
      "berkshire-hathaway",
      "control-situations"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1965-partnership-letter",
    "title": "Our Performance in 1965",
    "year": 1965,
    "summary": "Annual letter reporting 1965 results: partnership gained 47.2% vs the Dow's 14.2%, the widest margin in BPL's history. The partnership took effective control of Berkshire Hathaway. Buffett reflects on compounding, critiques institutional investment management, and discusses the joys and challenges of operating increasingly large capital.",
    "concepts": [
      "compounding",
      "intrinsic-value",
      "margin-of-safety",
      "opportunity-cost",
      "berkshire-hathaway"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1966-mid-year-letter",
    "title": "First Half Performance — July 1966",
    "year": 1966,
    "summary": "Mid-1966 report: BPL gained 8.2% vs the Dow's -8.7% in the first half. Topics include the Hochschild, Kohn & Co. acquisition (first entire business purchase by BPL), market forecasting philosophy, and institutional investment critique.",
    "concepts": [
      "margin-of-safety",
      "control-situations",
      "generals",
      "workouts",
      "intrinsic-value"
    ],
    "companies": [
      "berkshire-hathaway",
      "hochschild-kohn"
    ]
  },
  {
    "slug": "1967-midyear-letter",
    "title": "First Half Performance — July 1967",
    "year": 1967,
    "summary": "BPL gained 21% vs the Dow's 11.4% in first half 1967, a 9.6-point advantage. Discusses Berkshire Hathaway textile difficulties, Hochschild Kohn & Associated Cotton Shops acquisitions, and the DRC controlled company. Predicts substantial unrealized capital gains in 1967.",
    "concepts": [
      "margin-of-safety",
      "control-situations",
      "generals",
      "workouts",
      "intrinsic-value"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing"
    ]
  },
  {
    "slug": "1967-commitment-letter",
    "title": "Commitment Letter for 1968 — October 1967",
    "year": 1967,
    "summary": "The most famous partnership letter. Buffett announces a reduction in his performance target from '10 points better than the Dow' to '9% per annum or 5 points over the Dow.' Explains four reasons: fewer quantitative bargains, hyperactive markets, $65M capital base, and personal motivation. A candid self-assessment from age 37.",
    "concepts": [
      "opportunity-cost",
      "intrinsic-value",
      "margin-of-safety",
      "compounding"
    ],
    "companies": []
  },
  {
    "slug": "1968-midyear-letter",
    "title": "First Half Performance — 1968",
    "year": 1968,
    "summary": "Mid-year report for 1968. BPL gained 16% vs Dow's 0.9% in the first half. Buffett warned this was partly concentrated positions creating volatility, and that the revised limited objectives remain the right frame for long-term evaluation.",
    "concepts": [
      "value-investing",
      "compounding",
      "opportunity-cost"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing"
    ]
  },
  {
    "slug": "1969-midyear-letter",
    "title": "Announcement of Dissolution — May 1969",
    "year": 1969,
    "summary": "In this pivotal letter, Buffett formally announced his intention to dissolve the partnership at yearend 1969. He cited three reasons: quantitative investment opportunities had dried up, BPL's $100M size eliminated most small-cap ideas, and his desire to focus on non-investment activities. A frank self-assessment of his inability to 'slow down' while still publicly managing partners' capital.",
    "concepts": [
      "value-investing",
      "compounding",
      "opportunity-cost",
      "margin-of-safety"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing"
    ]
  },
  {
    "slug": "1969-controlled-companies",
    "title": "Diversified Retailing & Berkshire Hathaway — December 1969",
    "year": 1969,
    "summary": "Buffett provided partners with detailed information on BPL's two controlled companies — Diversified Retailing Company (DRC) and Berkshire Hathaway — and their principal operating businesses. Describes the sale of Hochschild Kohn, the Associated Retail Stores acquisition, the insurance operations (National Indemnity), and the Illinois National Bank.",
    "concepts": [
      "capital-allocation",
      "intrinsic-value",
      "insurance",
      "float"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing",
      "national-indemnity"
    ]
  },
  {
    "slug": "1969-dissolution-followup",
    "title": "Distribution Details & Q&A — December 1969",
    "year": 1969,
    "summary": "Detailed Q&A on the partnership dissolution covering: initial cash distribution (~64% of Jan 1 1969 capital, mailed Jan 5 1970), DRC and B-H stock distribution, Blue Chip Stamps, tax implications, and the March 31st deadline for bond purchase assistance.",
    "concepts": [
      "capital-allocation",
      "intrinsic-value"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing",
      "blue-chip-stamps"
    ]
  },
  {
    "slug": "1966-partnership-letter",
    "title": "The First Decade",
    "year": 1966,
    "summary": "The Partnership's 10th anniversary letter. BPL gained 20.4% vs the Dow's -15.6% — a record 36-point advantage. Buffett reflects candidly on the drying up of investment opportunities as capital grows, and analyzes performance in Controls, Generals, Workouts and Misc categories.",
    "concepts": [
      "intrinsic-value",
      "opportunity-cost",
      "compounding",
      "margin-of-safety",
      "workouts",
      "control-situations"
    ],
    "companies": [
      "berkshire-hathaway",
      "hochschild-kohn"
    ]
  },
  {
    "slug": "1967-partnership-letter",
    "title": "Our Performance in 1967",
    "year": 1967,
    "summary": "BPL gained 35.9% vs the Dow's 19.0% in 1967 — a record year. However, 95% of investment managers beat the Dow. Worst year ever in Workouts (0.89% return). Berkshire textile operations remain a drag; National Indemnity acquisition described as highly satisfactory. Moderated objectives from October letter discussed candidly.",
    "concepts": [
      "intrinsic-value",
      "opportunity-cost",
      "compounding",
      "margin-of-safety",
      "workouts",
      "control-situations",
      "float",
      "insurance",
      "capital-allocation"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing",
      "national-indemnity"
    ]
  },
  {
    "slug": "1968-partnership-letter",
    "title": "Our Performance in 1968",
    "year": 1968,
    "summary": "1968 was the best year in BPL history — 58.8% overall gain vs Dow's 7.7%. Buffett called this a 'freak' result like picking up thirteen spades in bridge. Despite record performance, he warned that the partnership would be dissolved at yearend 1969 and outlined the reasons for his continued pessimism about finding undervalued opportunities.",
    "concepts": [
      "value-investing",
      "intrinsic-value",
      "compounding",
      "margin-of-safety"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing",
      "national-indemnity"
    ]
  },
  {
    "slug": "1969-partnership-letter",
    "title": "Our Performance in 1969",
    "year": 1969,
    "summary": "The final full-year performance summary of the Buffett Partnership. BPL achieved a gain of approximately 6.7% for the year. Partners received a 64% cash distribution in January 1970, with the remaining assets distributed as DRC and B-H stock. This letter marks the formal conclusion of one of investment history's most remarkable records — 13 consecutive years of outperforming the Dow.",
    "concepts": [
      "compounding",
      "intrinsic-value",
      "capital-allocation"
    ],
    "companies": [
      "berkshire-hathaway",
      "diversified-retailing",
      "national-indemnity",
      "blue-chip-stamps"
    ]
  },
  {
    "slug": "1970-partnership-letter",
    "title": "Tax-Exempt Bond Guidance — February 1970",
    "year": 1970,
    "summary": "Written to help partners who received large cash distributions from BPL invest in tax-exempt municipal bonds. Buffett explained bond mechanics (bearer vs registered, coupon collection, custody accounts), discussed maturity and quality trade-offs, and committed to helping partners through March 31st before permanently closing his office.",
    "concepts": [
      "capital-allocation",
      "compounding"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1977-berkshire-letter",
    "title": "The Moat Speech - 1977",
    "year": 1977,
    "summary": "One of the most important letters in Berkshire history. Buffett introduced the \"economic moat\" concept - describing competitive advantage as a \"城堡\" (castle) with a protective moat. This letter laid out the framework for evaluating business quality that would guide Berkshire for decades.",
    "concepts": [
      "economic-moat",
      "competitive-advantage",
      "franchise",
      "roe",
      "capital-allocation"
    ],
    "companies": [
      "berkshire-hathaway",
      "buffalo-evening-news",
      "geico"
    ]
  },
  {
    "slug": "1985-berkshire-letter",
    "title": "The Textile Exit & Quality Companies - 1985",
    "year": 1985,
    "summary": "Buffett formally closed Berkshire's textile operations - marking the end of the business that started it all. The letter introduced the \"owner earnings\" concept as a truer measure of business value than accounting earnings, and discussed the acquisition of Scott & Fetzer.",
    "concepts": [
      "owner-earnings",
      "accounting-earnings",
      "acquisition",
      "goodwill",
      "cigar-butts"
    ],
    "companies": [
      "berkshire-hathaway",
      "scott-fetzer",
      "cap-cities"
    ]
  },
  {
    "slug": "1986-berkshire-letter",
    "title": "Coca-Cola & Annual Meeting Tradition - 1986",
    "year": 1986,
    "summary": "The letter highlighted Berkshire's investment in Coca-Cola and the nascent \"annual meeting\" tradition that would grow to become \"Woodstock of Capitalism.\" The meeting was becoming an increasingly important ritual for shareholders.",
    "concepts": [
      "compounding",
      "franchise",
      "economic-moat",
      "long-term-investing"
    ],
    "companies": [
      "berkshire-hathaway",
      "coca-cola",
      "geico"
    ]
  },
  {
    "slug": "1987-berkshire-letter",
    "title": "The Crash - 1987",
    "year": 1987,
    "summary": "Written after the October 1987 crash (22% in one day). Buffett explained that crashes are inevitable, unpredictable, and irrelevant to long-term investors. He made no major moves during the crash, having cash available but not deployed.",
    "concepts": [
      "compounding",
      "long-term-investing",
      "margin-of-safety",
      "intrinsic-value",
      "leverage"
    ],
    "companies": [
      "berkshire-hathaway",
      "geico"
    ]
  },
  {
    "slug": "1988-berkshire-letter",
    "title": "Coca-Cola & Federal Home Loan Bank - 1988",
    "year": 1988,
    "summary": "Buffett disclosed the massive Coca-Cola investment (cost $592.5 million, about 6.3% of Berkshire's net worth - at the time the largest single investment of Buffett's career) and explained the thinking behind buying wonderful businesses at fair prices.",
    "concepts": [
      "intrinsic-value",
      "fair-price",
      "wonderful-business",
      "economic-moat",
      "compounding"
    ],
    "companies": [
      "berkshire-hathaway",
      "coca-cola",
      "wells-fargo"
    ]
  },
  {
    "slug": "1996-berkshire-letter",
    "title": "The Circle of Competence - 1996",
    "year": 1996,
    "summary": "Buffett formalized the \"Circle of Competence\" concept and discussed Berkshire's investment in a variety of businesses. He also explained the challenges of capital allocation as Berkshire grew larger and the search for \"elephant-sized\" acquisitions.",
    "concepts": [
      "circle-of-competence",
      "capital-allocation",
      "acquisition",
      "compounding",
      "long-term-investing"
    ],
    "companies": [
      "berkshire-hathaway",
      "geico"
    ]
  },
  {
    "slug": "2005-berkshire-letter",
    "title": "GEICO's Transformation & The Hurricane Test - 2005",
    "year": 2005,
    "summary": "A year of contrasts: Buffett navigated record hurricane losses ($3.4B from Katrina, Rita and Wilma) while celebrating GEICO's extraordinary productivity gains - 32% improvement in two years. Five new acquisitions were announced, including Medical Protective, Forest River, Business Wire, Applied Underwriters, and PacifiCorp. A defining passage: \"Unlike many business buyers, Berkshire has no exit strategy. We buy to keep.\"",
    "concepts": [
      "compounding",
      "insurance-float",
      "capital-allocation",
      "acquisition",
      "intrinsic-value",
      "long-term-investing"
    ],
    "companies": [
      "berkshire-hathaway",
      "geico",
      "general-re",
      "midamerican",
      "pacificorp"
    ]
  },
  {
    "slug": "2008-berkshire-letter",
    "title": "The Financial Crisis - 2008",
    "year": 2008,
    "summary": "Written during the depths of the 2008 financial crisis. Buffett's famous \"buy American\" op-ed from October 2008 is summarized. He explained that economic Armageddon did not occur, and Berkshire emerged from the crisis stronger, having invested heavily while others panicked.",
    "concepts": [
      "intrinsic-value",
      "compounding",
      "margin-of-safety",
      "long-term-investing",
      "opportunity-cost"
    ],
    "companies": [
      "berkshire-hathaway",
      "geico",
      "byd",
      "moodys"
    ]
  },
  {
    "slug": "2016-berkshire-letter",
    "title": "The Apple Investment & Elephant Hunt - 2016",
    "year": 2016,
    "summary": "Berkshire disclosed its first major tech investment - Apple - and discussed the ongoing hunt for transformative acquisitions. Buffett also addressed the growing pile of cash (over $80 billion) and the challenge of deploying capital in an expensive market.",
    "concepts": [
      "capital-allocation",
      "intrinsic-value",
      "compounding",
      "fair-price",
      "circle-of-competence"
    ],
    "companies": [
      "berkshire-hathaway",
      "apple",
      "geico",
      "burlington-northern-santa-fe"
    ]
  },
  {
    "slug": "2020-berkshire-letter",
    "title": "The Pandemic Year - 2020",
    "year": 2020,
    "summary": "Written during the COVID-19 pandemic. Buffett acknowledged the human tragedy while remaining optimistic about America's long-term economic resilience. He made a historic pivot: selling airline stocks, and writing off most of the Precision Castparts acquisition.",
    "concepts": [
      "compounding",
      "long-term-investing",
      "capital-allocation",
      "acquisition",
      "intrinsic-value"
    ],
    "companies": [
      "berkshire-hathaway",
      "dominion-energy",
      "burlington-northern-santa-fe"
    ]
  },
  {
    "slug": "2025-berkshire-letter",
    "title": "Gregory Abel's First Letter - 2025",
    "year": 2025,
    "summary": "Gregory Abel's first shareholder letter as CEO, written after Warren Buffett's passing in early 2025. Abel opens by celebrating Buffett's legacy before laying out his own vision for Berkshire: strengthened culture and values, the enduring insurance franchise ($176B float), and disciplined capital allocation under new leadership. The letter demonstrates continuity with Buffett's philosophy while signaling a new chapter.",
    "concepts": [
      "compounding",
      "capital-allocation",
      "intrinsic-value",
      "economic-moat",
      "long-term-investing",
      "acquisition",
      "deferred-tax-liability"
    ],
    "companies": [
      "berkshire-hathaway",
      "geico",
      "apple",
      "coca-cola",
      "american-express",
      "burlington-northern-santa-fe"
    ]
  },
  {
    "slug": "1978-berkshire-letter",
    "title": "Steady Progress - 1978",
    "year": 1978,
    "summary": "1978 was a year of solid progress. GEICO's turnaround continued to contribute to earnings while investment portfolio performed well.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1979-berkshire-letter",
    "title": "Diversified Strength - 1979",
    "year": 1979,
    "summary": "1979 showed mixed results. Textile operations faced challenges while insurance and investments provided steady contributions.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1980-berkshire-letter",
    "title": "Patient Capital - 1980",
    "year": 1980,
    "summary": "1980 saw continued difficult conditions in some businesses. Buffett discussed the importance of intrinsic value and long-term thinking.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1981-berkshire-letter",
    "title": "Strategic Positioning - 1981",
    "year": 1981,
    "summary": "1981 was a year of careful navigation. The focus remained on building durable businesses with strong franchise values.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1982-berkshire-letter",
    "title": "Capital Allocation - 1982",
    "year": 1982,
    "summary": "1982 marked a year of strategic positioning. Insurance operations showed strong performance while seeking new investment opportunities.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1983-berkshire-letter",
    "title": "Franchise Value - 1983",
    "year": 1983,
    "summary": "1983 saw excellent results. See's Candy and other controlled businesses contributed strongly while the investment portfolio appreciated.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1984-berkshire-letter",
    "title": "The Wide Moat - 1984",
    "year": 1984,
    "summary": "1984 was another strong year. Buffett discussed the concept of 'wide moats' around businesses and the importance of franchise value.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1989-berkshire-letter",
    "title": "Insurance Float - 1989",
    "year": 1989,
    "summary": "1989 saw continued progress. The insurance float became increasingly valuable while investment gains contributed to overall performance.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1990-berkshire-letter",
    "title": "Recession Navigation - 1990",
    "year": 1990,
    "summary": "1990 brought a recession in the early 1990s. Berkshire's diversified operations and patient approach served well during uncertain times.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1991-berkshire-letter",
    "title": "Resilience - 1991",
    "year": 1991,
    "summary": "1991 showed strong performance despite economic uncertainty. The insurance operations continued to generate valuable float.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1992-berkshire-letter",
    "title": "Durable Advantages - 1992",
    "year": 1992,
    "summary": "1992 was a year of solid results. Capital allocation remained focused on businesses with durable competitive advantages.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1993-berkshire-letter",
    "title": "Quality at Reasonable Price - 1993",
    "year": 1993,
    "summary": "1993 saw continued progress. The investment philosophy of buying quality businesses at reasonable prices continued to drive results.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1994-berkshire-letter",
    "title": "Patient Capital - 1994",
    "year": 1994,
    "summary": "1994 marked another strong year. Berkshire's diverse businesses and investment portfolio contributed to shareholder value.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1995-berkshire-letter",
    "title": "The GEICO Transformation - 1995",
    "year": 1995,
    "summary": "1995 was a landmark year with the acquisition of GEICO. This transformed Berkshire's insurance operations significantly.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1997-berkshire-letter",
    "title": "Strong Performance - 1997",
    "year": 1997,
    "summary": "1997 saw strong performance driven by insurance operations and investment gains. The market environment favored patient capital allocation.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1998-berkshire-letter",
    "title": "Global Expansion - 1998",
    "year": 1998,
    "summary": "1998 was a year of major acquisitions including General Re. This expanded Berkshire's insurance operations globally.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2000-berkshire-letter",
    "title": "Dot-Com Reckoning - 2000",
    "year": 2000,
    "summary": "2000 marked a year of transition as the dot-com bubble began to deflate. Berkshire's value approach proved its worth.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2001-berkshire-letter",
    "title": "Resilience After Crisis - 2001",
    "year": 2001,
    "summary": "2001 was a challenging year following September 11. Insurance operations faced significant claims but the diversified businesses showed resilience.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2002-berkshire-letter",
    "title": "Financial Strength - 2002",
    "year": 2002,
    "summary": "2002 saw strong performance from insurance and investments. Berkshire's financial strength allowed it to take advantage of opportunities.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2003-berkshire-letter",
    "title": "Economic Recovery - 2003",
    "year": 2003,
    "summary": "2003 marked continued progress. The economic recovery benefited many of Berkshire's operating businesses.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2004-berkshire-letter",
    "title": "Solid Progress - 2004",
    "year": 2004,
    "summary": "2004 was a solid year. Insurance operations continued to generate valuable float while operating businesses performed well.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2006-berkshire-letter",
    "title": "Strong Performance - 2006",
    "year": 2006,
    "summary": "2006 saw strong performance across all businesses. The investment portfolio benefited from favorable market conditions.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2007-berkshire-letter",
    "title": "Excellent Results - 2007",
    "year": 2007,
    "summary": "2007 was a year of excellent results before the financial crisis. Buffett discussed the importance of liquidity and financial strength.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2009-berkshire-letter",
    "title": "Crisis Navigation - 2009",
    "year": 2009,
    "summary": "2009 was a challenging year during the financial crisis but Berkshire's strong position allowed strategic moves.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2010-berkshire-letter",
    "title": "Recovery Year - 2010",
    "year": 2010,
    "summary": "2010 saw a recovery in results. The diverse businesses benefited from economic improvement.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2011-berkshire-letter",
    "title": "Continued Progress - 2011",
    "year": 2011,
    "summary": "2011 was a year of continued progress. Insurance operations performed well while investments contributed to results.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2013-berkshire-letter",
    "title": "Annual Letter - 2013",
    "year": 2013,
    "summary": "2013 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2014-berkshire-letter",
    "title": "Annual Letter - 2014",
    "year": 2014,
    "summary": "2014 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2015-berkshire-letter",
    "title": "Annual Letter - 2015",
    "year": 2015,
    "summary": "2015 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2017-berkshire-letter",
    "title": "Annual Letter - 2017",
    "year": 2017,
    "summary": "2017 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2018-berkshire-letter",
    "title": "Annual Letter - 2018",
    "year": 2018,
    "summary": "2018 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2019-berkshire-letter",
    "title": "Annual Letter - 2019",
    "year": 2019,
    "summary": "2019 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2021-berkshire-letter",
    "title": "Annual Letter - 2021",
    "year": 2021,
    "summary": "2021 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2022-berkshire-letter",
    "title": "Annual Letter - 2022",
    "year": 2022,
    "summary": "2022 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2023-berkshire-letter",
    "title": "Annual Letter - 2023",
    "year": 2023,
    "summary": "2023 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "2024-berkshire-letter",
    "title": "Annual Letter - 2024",
    "year": 2024,
    "summary": "2024 was a year of progress for Berkshire Hathaway with solid performance across insurance and investment operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1971-berkshire-letter",
    "title": "Year of Transition - 1971",
    "year": 1971,
    "summary": "1971 was a pivotal year as Buffett fully took control of Berkshire. The textile business showed mixed results while insurance operations began to contribute meaningfully. This marked the beginning of Berkshire's transformation from a struggling textile company to an investment powerhouse.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1972-berkshire-letter",
    "title": "Building Foundations - 1972",
    "year": 1972,
    "summary": "1972 saw improved performance across Berkshire's operations. Insurance underwriting benefited from favorable market conditions. The investment portfolio showed gains while Buffett continued to look for acquisition opportunities.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1973-berkshire-letter",
    "title": "Weathering the Storm - 1973",
    "year": 1973,
    "summary": "1973 was a challenging year with the market decline. Berkshire's diversified operations helped weather the storm while maintaining the investment approach. This period demonstrated the value of having businesses with strong cash generation.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1974-berkshire-letter",
    "title": "Patience Pays - 1974",
    "year": 1974,
    "summary": "1974 brought a severe market decline. Buffett used the downturn to make strategic acquisitions and investments at attractive valuations. The partnership approach to investing continued while building the insurance operations.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1975-berkshire-letter",
    "title": "Finding Opportunities - 1975",
    "year": 1975,
    "summary": "1975 saw continued market weakness but also created opportunities. Insurance operations began to show better results. The focus remained on building businesses with strong competitive advantages.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  },
  {
    "slug": "1976-berkshire-letter",
    "title": "Rising from the Asches - 1976",
    "year": 1976,
    "summary": "1976 marked continued progress and the beginning of GEICO's turnaround under new management. Insurance operations improved significantly. This year was crucial in establishing Berkshire's insurance-focused business model.",
    "concepts": [
      "intrinsic-value",
      "moat",
      "compounding",
      "owner-earnings"
    ],
    "companies": [
      "berkshire-hathaway"
    ]
  }
]

export const CONCEPTS_DATA: Array<{
  slug: string
  name: string
  definition: string
}> = [
  {
    "slug": "intrinsic-value",
    "name": "Intrinsic Value",
    "definition": "The discounted value of the cash that can be taken out of a business during its remaining life. It is an estimate rather than a precise figure, and is necessarily subjective. The two key variables are future cash flows and the appropriate discount rate."
  },
  {
    "slug": "margin-of-safety",
    "name": "Margin of Safety",
    "definition": "The principle of only buying securities when their market price is significantly below their intrinsic value, providing a cushion against errors in calculation or unforeseen developments. First articulated by Benjamin Graham."
  },
  {
    "slug": "economic-moat",
    "name": "Economic Moat",
    "definition": "A sustainable competitive advantage that allows a business to fend off competitors and maintain high returns on capital for long periods. Buffett described it as a \"城堡\" (castle) protected by a moat — the wider and more durable the moat, the more valuable the business."
  },
  {
    "slug": "owner-earnings",
    "name": "Owner Earnings",
    "definition": "Net income plus depreciation, depletion, and amortization, minus the average annual amount of capital expenditures required to maintain the business at its current competitive position. Buffett's preferred measure of corporate profitability over reported accounting earnings."
  },
  {
    "slug": "circle-of-competence",
    "name": "Circle of Competence",
    "definition": "The area around an investor's genuine expertise — businesses and industries they understand well enough to evaluate with reasonable confidence. Buffett emphasizes staying within this circle rather than attempting to evaluate businesses outside it."
  },
  {
    "slug": "free-cash-flow",
    "name": "Free Cash Flow",
    "definition": "The cash generated by a business after all operating expenses, capital expenditures, and working capital investments. Buffett uses this to evaluate whether a business is a \"cash machine\" or \"cash consumer.\""
  },
  {
    "slug": "roe",
    "name": "Return on Equity (ROE)",
    "definition": "Net income divided by shareholders' equity. Buffett pays close attention to this metric, noting that a business earning high ROE on little or no equity is far superior to one earning low ROE on a large equity base."
  },
  {
    "slug": "roe-on-equity",
    "name": "ROE on Equity (minimal equity)",
    "definition": "A business that generates high returns on equity while requiring minimal net tangible assets is exceptionally valuable. This is the hallmark of an \"asset-light\" or \"franchise\" business."
  },
  {
    "slug": "franchise",
    "name": "Franchise Business",
    "definition": "A business that sells a product or service that is needed or desired by customers, is not substituable, and is not regulated by a commodity-like pricing structure. Franchises can sustain pricing power and high ROE indefinitely."
  },
  {
    "slug": "competitive-advantage",
    "name": "Competitive Advantage",
    "definition": "A structural characteristic of a business that allows it to consistently earn returns on capital above its cost of capital. Often synonymous with economic moat, but broader in scope."
  },
  {
    "slug": "compounding",
    "name": "Compounding",
    "definition": "The process by which earnings are reinvested to generate additional earnings over time. Buffett describes compounding as the most powerful force in investing and has made it the cornerstone of Berkshire's capital allocation strategy."
  },
  {
    "slug": "long-term-investing",
    "name": "Long-Term Investing",
    "definition": "The strategy of buying securities with the intention of holding them for a very long period — ideally forever. Buffett's quote: \"Our favorite holding period is forever.\" Emphasizes the benefits of minimizing taxes and transaction costs."
  },
  {
    "slug": "value-investing",
    "name": "Value Investing",
    "definition": "The discipline of buying securities for less than their intrinsic value and holding them until the market corrects the mispricing. Originated with Benjamin Graham and David Dodd, refined by Buffett into \"quality at a reasonable price\" (GARP/QARP)."
  },
  {
    "slug": "capital-allocation",
    "name": "Capital Allocation",
    "definition": "The process of deploying the cash generated by a business — or received from operations — into the highest-return uses: reinvestment in the business, acquisitions, dividends, or share repurchases. Buffett considers this the CEO's most important job."
  },
  {
    "slug": "share-repurchase",
    "name": "Share Repurchase",
    "definition": "When a company buys back its own shares, increasing the ownership stake of remaining shareholders. Buffett will repurchase Berkshire shares when they trade below intrinsic value, calling it the \"most attractive capital allocation decision\" available."
  },
  {
    "slug": "acquisition",
    "name": "Acquisitions",
    "definition": "Buying entire businesses. Buffett's criteria: good businesses (high ROE, durable moat), at fair prices rather than bargain prices, run by honest and competent managers. Avoids synergies, diversification-for-its-own-sake, and companies in distress."
  },
  {
    "slug": "deferred-tax-liability",
    "name": "Deferred Tax Liability",
    "definition": "An accounting liability representing future taxes that will be paid when appreciated securities are sold. Buffett views unrealized gains as creating a \"deferred tax liability\" that must be considered when evaluating intrinsic value."
  },
  {
    "slug": "float",
    "name": "Insurance Float",
    "definition": "The money that insurance companies hold between收取 premiums and paying claims. For Berkshire's reinsurance operations, float is essentially \"free\" capital that can be invested at high returns. Buffett describes it as the \"Gitl\" (little girl) that Berkshire has been raising."
  },
  {
    "slug": "weighted-average-cost-of-capital",
    "name": "Weighted Average Cost of Capital (WACC)",
    "definition": "The average cost of all capital (debt and equity) used to finance a business. Buffett focuses on whether a business earns returns above its cost of capital as the fundamental test of value creation."
  },
  {
    "slug": "covenant",
    "name": "Non-Compete Covenant",
    "definition": "An agreement in an acquisition contract preventing sellers from competing with the buyer. In the context of small business acquisitions, Buffett notes these are largely unenforceable and should be ignored in valuation."
  },
  {
    "slug": "debt-free",
    "name": "Debt-Free Operation",
    "definition": "A business with no significant debt obligations. Buffett prefers businesses that operate with little or no debt, as they are more resilient during economic downturns and avoid the agency problems associated with leverage."
  },
  {
    "slug": "enterprise-value",
    "name": "Enterprise Value",
    "definition": "Market capitalization plus debt minus cash. Represents the true cost of acquiring a business. Buffett prefers to think in terms of enterprise value and the cash generated relative to that cost."
  },
  {
    "slug": "cigar-butts",
    "name": "Cigar Butt Investing",
    "definition": "Buying cheap businesses — \"cigar butts\" — at very low prices, hoping to profit from a final puff (asset liquidation) rather than future earnings. Buffett abandoned this Grahamian approach in the mid-1970s in favor of buying \"wonderful businesses at fair prices.\""
  },
  {
    "slug": "wonderful-business",
    "name": "Wonderful Business",
    "definition": "A business with durable competitive advantages, excellent management, and the ability to compound value over decades. Buffett's evolved strategy: It is far better to buy a wonderful business at a fair price than a fair business at a wonderful price."
  },
  {
    "slug": "fair-price",
    "name": "Fair Price",
    "definition": "The price at which a wonderful business can be purchased without overpaying. Buffett uses intrinsic value as the anchor for determining a fair price, paying less attention to the precise moment of purchase than to the quality of the business."
  },
  {
    "slug": "ovetp",
    "name": "Over-the-Counter (OTC) Stocks",
    "definition": "Stocks traded over-the-counter rather than on major exchanges. Buffett's early returns were significantly boosted by finding undervalued OTC stocks that required detailed analytical work to identify."
  },
  {
    "slug": "seth",
    "name": "Sanford Eol (Seth) — Berkshire Shareholder",
    "definition": "The fictional character of a hypothetical long-term Berkshire shareholder, invented by Buffett to illustrate the experience of passive Berkshire owners who benefited enormously from compounding without ever needing to act."
  },
  {
    "slug": "bet",
    "name": "The Bet (Long-Term vs. Hedge Funds)",
    "definition": "In 2007, Buffett bet $1 million that a low-cost S&P 500 index fund would outperform a hedge fund portfolio over 10 years. The bet ended in 2017 with the index fund winning decisively. Used to illustrate the futility of high fees in active management."
  },
  {
    "slug": "second-level-thinking",
    "name": "Second-Level Thinking",
    "definition": "Thinking that goes beyond the conventional consensus. First-level thinking is simplistic and inward-looking; second-level thinking requires understanding what others think and why, and then making a better decision."
  },
  {
    "slug": "institutional-imperative",
    "name": "Institutional Imperative",
    "definition": "The tendency of organizations to imitate each other's behavior regardless of logic or results. Buffett's term for the irrational conformity in corporate decision-making, where managers follow industry peers into value-destroying acquisitions and strategies."
  },
  {
    "slug": "manager-bias",
    "name": "Manager Bias",
    "definition": "The tendency of CEOs to expand their empires regardless of returns on capital, often citing \"synergies\" that rarely materialize. Buffett specifically warns against CEOs who consistently overpay for acquisitions."
  },
  {
    "slug": "derivatives",
    "name": "Derivatives",
    "definition": "Financial instruments whose value is derived from underlying assets. Buffett has repeatedly called derivatives \"weapons of mass destruction\" due to their potential to amplify systemic risk and create large, hard-to-measure liabilities."
  },
  {
    "slug": "accounting-earnings",
    "name": "Accounting Earnings vs. Economic Earnings",
    "definition": "The divergence between reported accounting earnings and true economic earnings. Buffett emphasizes that GAAP accounting can create misleading impressions — goodwill amortization, inventory methods, and depreciation can all distort reported figures."
  },
  {
    "slug": "goodwill",
    "name": "Goodwill",
    "definition": "The premium paid over book value in an acquisition. Buffett distinguishes between \"goodwill\" that represents genuine economic value (from durable competitive advantages) and goodwill that is merely accounting goodwill with no real significance."
  },
  {
    "slug": "debt-ratio",
    "name": "Debt Ratio",
    "definition": "The proportion of debt relative to equity or total capital. Buffett prefers businesses with modest or no debt, and uses the debt ratio as one signal of a business's financial resilience and management discipline."
  },
  {
    "slug": "look-through-earnings",
    "name": "Look-Through Earnings",
    "definition": "Berkshire's reported earnings that include only Berkshire's operational results, excluding the earnings of investees that are accounted for as equity holdings. Buffett introduced this concept to give shareholders a clearer picture of Berkshire's true operating performance."
  },
  {
    "slug": "headline-risk",
    "name": "Headline Risk",
    "definition": "The risk that a business will suffer permanent damage to its reputation and earnings from adverse publicity. Buffett notes that businesses with strong brands and durable moats are generally resistant to headline risk, while those without are vulnerable."
  },
  {
    "slug": "indexing",
    "name": "Index Fund Investing",
    "definition": "Buying a broad market index fund rather than attempting to pick individual securities. Buffett has explicitly recommended that most investors should use index funds, reserving active management for investors with genuine expertise."
  },
  {
    "slug": "time-value-of-money",
    "name": "Time Value of Money",
    "definition": "The concept that a dollar today is worth more than a dollar in the future due to its potential earning capacity. This principle underlies Buffett's use of discounted cash flow (DCF) analysis to calculate intrinsic value."
  },
  {
    "slug": "discounted-cash-flow",
    "name": "Discounted Cash Flow (DCF)",
    "definition": "A valuation method that estimates the present value of an investment based on its expected future cash flows, discounted at an appropriate rate. Buffett uses DCF as a conceptual tool rather than a precise formula."
  },
  {
    "slug": "liquidation-value",
    "name": "Liquidation Value",
    "definition": "The value of a business if all assets were sold and liabilities paid off. Graham's approach of buying stocks below liquidation value (the \"net-net\" strategy) was the foundation of early Buffett Partnership returns."
  },
  {
    "slug": "tax-efficiency",
    "name": "Tax Efficiency",
    "definition": "The advantage of holding stocks for long periods rather than trading frequently. Long-term capital gains are taxed at lower rates, and taxes are deferred until gains are realized — allowing compounding on pre-tax capital."
  },
  {
    "slug": "opportunity-cost",
    "name": "Opportunity Cost",
    "definition": "The return foregone by choosing one investment over the next best alternative. Buffett applies opportunity cost rigorously, preferring to hold cash rather than invest in marginal opportunities that don't meet his return thresholds."
  },
  {
    "slug": "cash-cow",
    "name": "Cash Cow",
    "definition": "A business that generates more cash than it needs for reinvestment and pays out the excess to owners. Buffett uses this term to describe businesses with durable competitive advantages that require minimal capital investment to maintain."
  },
  {
    "slug": "conglomerate-discount",
    "name": "Conglomerate Discount",
    "definition": "The tendency of diversified conglomerates to trade at a discount to the sum of their parts. Buffett has used this to Berkshire's advantage, sometimes spinning off divisions at a premium to their intrinsic value."
  },
  {
    "slug": "covenant",
    "name": "Covenant (Non-Compete)",
    "definition": "Agreements in business sales preventing sellers from competing. Buffett notes these are largely unenforceable in practice, so they should carry no weight in business valuation."
  },
  {
    "slug": "synergy",
    "name": "Synergy",
    "definition": "Cost savings or revenue enhancements claimed from combining two businesses. Buffett is deeply skeptical of synergy-driven acquisitions, noting that most promised synergies fail to materialize."
  },
  {
    "slug": "tender-offer",
    "name": "Tender Offer",
    "definition": "A public offer to buy shares directly from shareholders at a premium price. Buffett has used tender offers strategically (e.g., for See's Candies) and criticized defensive tactics that prevent them."
  },
  {
    "slug": "leverage",
    "name": "Leverage",
    "definition": "Using borrowed money to amplify investment returns. Buffett has consistently avoided leverage except in rare circumstances, noting that leverage magnifies both gains and losses and can permanently impair capital."
  }
]

export const COMPANIES_DATA: Array<{
  slug: string
  name: string
  industry: string
}> = [
  {
    "slug": "berkshire-hathaway",
    "name": "Berkshire Hathaway",
    "industry": "Conglomerate / Holding Company"
  },
  {
    "slug": "national-indemnity",
    "name": "National Indemnity",
    "industry": "Insurance / Reinsurance"
  },
  {
    "slug": "see-candies",
    "name": "See's Candies",
    "industry": "Consumer Staples / Confectionery"
  },
  {
    "slug": "wisconsin-ice",
    "name": "Washington Post",
    "industry": "Media / Publishing"
  },
  {
    "slug": "times-mirror",
    "name": "GEICO",
    "industry": "Insurance / Auto Insurance"
  },
  {
    "slug": "buffalo-evening-news",
    "name": "Buffalo Evening News",
    "industry": "Media / Newspaper"
  },
  {
    "slug": "federated-department-stores",
    "name": "Federated Department Stores",
    "industry": "Retail"
  },
  {
    "slug": "多元零售",
    "name": "Blue Chip Stamps",
    "industry": "Finance / Trading Stamps"
  },
  {
    "slug": "rex-company",
    "name": "Rex",
    "industry": "Manufacturing / Shoe Machinery"
  },
  {
    "slug": "scott-fetzer",
    "name": "Scott & Fetzer",
    "industry": "Manufacturing / Diversified"
  },
  {
    "slug": "cap-cities",
    "name": "Capital Cities/ABC",
    "industry": "Media / Broadcasting"
  },
  {
    "slug": "first-national-bank",
    "name": "First National Omaha",
    "industry": "Banking"
  },
  {
    "slug": "us-airways",
    "name": "USAir",
    "industry": "Aviation / Airline"
  },
  {
    "slug": "pacificorp",
    "name": "PacificCorp",
    "industry": "Utilities / Energy"
  },
  {
    "slug": "greeley-co",
    "name": "Greeley坊",
    "industry": "Manufacturing / Shoe"
  },
  {
    "slug": "dexterity-shoes",
    "name": "Dexterity Shoes",
    "industry": "Manufacturing / Shoe"
  },
  {
    "slug": "david-lloyd",
    "name": "General Re",
    "industry": "Insurance / Reinsurance"
  },
  {
    "slug": "uscharter",
    "name": "U.S. Freightways",
    "industry": "Transportation / Freight"
  },
  {
    "slug": "midamerican",
    "name": "MidAmerican Energy Holdings",
    "industry": "Utilities / Energy"
  },
  {
    "slug": "burlington-northern-santa-fe",
    "name": "Burlington Northern Santa Fe (BNSF)",
    "industry": "Transportation / Railroad"
  },
  {
    "slug": "ibm",
    "name": "IBM",
    "industry": "Technology / IT Services"
  },
  {
    "slug": "byd",
    "name": "BYD",
    "industry": "Automotive / Electric Vehicles"
  },
  {
    "slug": "coca-cola",
    "name": "Coca-Cola",
    "industry": "Consumer Staples / Beverages"
  },
  {
    "slug": "american-express",
    "name": "American Express",
    "industry": "Financial Services / Payments"
  },
  {
    "slug": "wells-fargo",
    "name": "Wells Fargo",
    "industry": "Banking / Financial Services"
  },
  {
    "slug": "johnson-johnson",
    "name": "Johnson & Johnson",
    "industry": "Healthcare / Pharmaceuticals"
  },
  {
    "slug": "procter-gamble",
    "name": "Procter & Gamble",
    "industry": "Consumer Staples / Household Products"
  },
  {
    "slug": "moodys",
    "name": "Moody's",
    "industry": "Financial Services / Credit Rating"
  },
  {
    "slug": "apple",
    "name": "Apple",
    "industry": "Technology / Consumer Electronics"
  },
  {
    "slug": "jpmorgan-chase",
    "name": "JPMorgan Chase",
    "industry": "Banking / Financial Services"
  },
  {
    "slug": "amazon",
    "name": "Amazon",
    "industry": "Technology / E-Commerce"
  },
  {
    "slug": "dominion-energy",
    "name": "Dominion Energy",
    "industry": "Utilities / Energy"
  }
]
