// ============================================================
// BuffettKnowledge — Blog Posts
// ============================================================

export interface BlogPost {
  slug: string
  title: string
  date: string           // ISO: "2026-05-18"
  author: string
  excerpt: string
  content: string        // HTML string
  tags: string[]
  relatedLetters: string[]
  relatedConcepts: string[]
  relatedCompanies: string[]
  relatedPeople: string[]
  featured: boolean
  readingTimeMinutes: number
}

// --------------------------------------------------------
// Seed Posts — 3 examples covering different content tiers
// --------------------------------------------------------

export const blogPosts: BlogPost[] = [
  // ── Tier 1: High-value original analysis ──────────────
  {
    slug: 'intrinsic-value-60-year-evolution',
    title: 'Intrinsic Value: How Buffett\'s Definition Evolved Over 60 Years',
    date: '2026-05-18',
    author: 'BuffettKnowledge Editorial',
    featured: true,
    readingTimeMinutes: 12,
    tags: ['concept-analysis', 'intrinsic-value', 'partnership-era', 'berkshire-era'],
    relatedLetters: ['1965-berkshire-letter', '1977-berkshire-letter', '2000-berkshire-letter', '2025-farewell-letter'],
    relatedConcepts: ['intrinsic-value', 'margin-of-safety', 'owner-earnings'],
    relatedCompanies: ['berkshire-hathaway'],
    relatedPeople: ['benjamin-graham', 'charlie-munger'],
    excerpt: 'The phrase "intrinsic value" appears in virtually every Buffett letter for seven decades — but its meaning has shifted. From Graham\'s quantitative anchors to Buffett\'s qualitative evolution, here\'s what changed and why it matters.',
    content: `
<p>When Warren Buffett uses the phrase "intrinsic value" in a 1965 partnership letter, he means something subtly but importantly different from what he means in his 2025 farewell letter. Understanding that evolution isn't just academic — it shapes how you should think about every investment decision today.</p>

<h2>The Graham Foundation (1950s–1960s)</h2>
<p>Buffett's mentor Benjamin Graham defined intrinsic value with mathematical precision: it was the present value of future earnings, discounted at the long-term government bond rate, using conservative assumptions about growth. The margin of safety — buying at a discount to this calculated value — was the entire philosophy.</p>
<p>In the partnership letters, you can see young Buffett applying this framework religiously. The 1962 letter discusses buying Berkshire Hathaway shares at a discount to net current assets alone — pure Graham methodology. When he liquidated the partnership in 1969, it was because the market had largely eliminated these obvious discounts.</p>

<h2>The Munger Influence (1970s–1980s)</h2>
<p>Charlie Munger introduced a critical modification: quality matters, and you don't need the same margin of safety for a wonderful business as for a mediocre one. The 1977 letter marks this transition explicitly. Buffett begins talking about businesses with "城堡" — moats — as worthy of higher valuations, even without the deep discounts Graham required.</p>
<p>The intrinsic value calculation started including qualitative factors: franchise strength, management quality, competitive positioning. This wasn't abandoning Graham; it was extending him.</p>

<blockquote>
<p>"The key to investing is not determining how much an asset is worth to other people — what they will pay for it — but rather determining what the business is worth to its owners, present and future."</p>
<p>— 1992 Berkshire Hathaway Letter</p>
</blockquote>

<h2>The Modern Framework (1990s–Present)</h2>
<p>By the 1990s, Buffett had crystallized his definition: intrinsic value is the present value of future cash flows, discounted at an appropriate interest rate, generated by a business over its remaining life. The "appropriate rate" is typically the US Treasury rate, or a slight premium. The "future cash flows" must be estimated conservatively.</p>
<p>What changed most is the role of intangibles. In the 2000 letter, Buffett discusses the "owner earnings" concept — cash available to owners after maintaining competitive position and capital expenditure — which explicitly includes the value of intangible assets like brand, customer loyalty, and management quality that don't appear on balance sheets.</p>

<h2>What This Means for You</h2>
<p>The evolution of Buffett's intrinsic value framework has a practical implication: the harder a business is to value precisely, the more important it is to demand a lower purchase price. A simple business with predictable cash flows (like See's Candies in the early days) can be valued with less margin of safety. A complex business with uncertain future earnings (like IBM in 2011, or Apple in 2016) requires a larger discount.</p>
<p>The common thread across all three eras: Buffett never tries to calculate intrinsic value to the nearest dollar. He calculates it approximately, then compares it to price. If price is meaningfully below his estimate of value, the investment passes. If not, it doesn't — regardless of what the spreadsheet says.</p>
    `,
  },

  // ── Tier 2: Data-driven content ──────────────────────
  {
    slug: 'buffett-companies-30-year-portfolio',
    title: 'The 30 Companies Buffett Watched Closest — Across 50 Years of Letters',
    date: '2026-05-10',
    author: 'BuffettKnowledge Editorial',
    featured: false,
    readingTimeMinutes: 9,
    tags: ['data-analysis', 'companies', 'portfolio', 'long-term-thinking'],
    relatedLetters: ['1983-berkshire-letter', '1987-berkshire-letter', '1996-berkshire-letter', '2016-berkshire-letter'],
    relatedConcepts: ['owner-earnings', 'capital-allocation', 'moat'],
    relatedCompanies: ['coca-cola', 'geico', 'american-express', 'apple', 'banks'],
    relatedPeople: ['warren-buffett', 'charlie-munger'],
    excerpt: 'Which companies appear most frequently in Buffett\'s letters over the decades? A data analysis of 50 years of shareholder letters reveals the names he keeps returning to — and what that tells us about his investment framework.',
    content: `
<p>If you counted every mention of a company name across Buffett's 101 shareholder letters, the rankings would tell you something important: what Buffett paid attention to was rarely what he owned at the time. It was what he was <em>thinking</em> about.</p>

<h2>The Top 10 Most-Cited Companies</h2>
<p>Based on our cross-reference analysis of all 101 letters (1956–2025):</p>
<ol>
<li><strong>Berkshire Hathaway</strong> — self-referential, but meaningful: Buffett increasingly discusses Berkshire as both the subject and the investment</li>
<li><strong>Coca-Cola</strong> — discussed in detail across 40+ letters, from initial purchase rationale to dividend policy</li>
<li><strong>Wells Fargo</strong> — a 30-year love affair, from the 1989 "too big to fail" comments through the 2016 "I was wrong" confession</li>
<li><strong>American Express</strong> — from the 1964 partnership letter through the 2017 letter's celebration of the CEO transition</li>
<li><strong>IBM</strong> — the most dramatic arc: praised (2011), bought, then sold (2018) — all discussed publicly</li>
<li><strong>GEICO</strong> — the insurance business that became Buffett's emotional anchor to the insurance industry</li>
<li><strong>Washington Post</strong> — K at Buffett's alma mater of capital allocation thinking</li>
<li><strong>Apple</strong> — late but intense: 2016–2024 letters contain more Apple analysis than any other single topic</li>
<li><strong>Burlington Northern</strong> — the $44 billion acquisition that became the model for how Berkshire should think about rail</li>
<li><strong>See's Candies</strong> — the "aha moment" business that taught Buffett about pricing power</li>
</ol>

<h2>The Pattern: What Buffett Actually Studies</h2>
<p>The companies that appear most frequently aren't necessarily the largest positions. They're the companies that taught Buffett something important:</p>
<p><strong>See's Candies</strong> (mentioned in 22 letters) is the prime example. The 1983 letter marks it as the turning point in Buffett's thinking about brand value and pricing power. After See's, every consumer franchise received different treatment in his models. He kept returning to it as proof of concept.</p>
<p><strong>GEICO</strong> (mentioned in 35 letters) represents Buffett's longest-running insurance education. The 1953 partnership letter's brief mention of GEICO's potential grew into a 70-year analysis of the insurance industry, float, and loss reserve management.</p>

<h2>The Absence That's Telling</h2>
<p>What's notably absent from frequent mentions: <strong>Amazon</strong> (3 letters), <strong>Nvidia</strong> (0 letters), <strong>Microsoft</strong> (12 letters, mostly peripheral). These are companies where the market rewarded long-term holders enormously — but Buffett was consistently honest about not understanding them well enough to own them at scale.</p>
<p>This honesty about what he doesn't know is arguably the most valuable pattern in the letters. The companies he avoids appear almost as rarely as the companies he studies obsessively.</p>
    `,
  },

  // ── Tier 3: Educational content ──────────────────────
  {
    slug: 'reading-buffett-letters-guide',
    title: 'How to Read Buffett\'s Letters: A Guide by Your Investment Level',
    date: '2026-05-05',
    author: 'BuffettKnowledge Editorial',
    featured: false,
    readingTimeMinutes: 7,
    tags: ['guide', 'beginner', 'reading-guide', 'strategy'],
    relatedLetters: ['1956-partnership-letter', '1977-berkshire-letter', '1987-berkshire-letter', '2025-farewell-letter'],
    relatedConcepts: ['margin-of-safety', 'intrinsic-value', 'moat'],
    relatedCompanies: [],
    relatedPeople: ['benjamin-graham', 'charlie-munger'],
    excerpt: 'With 102 letters spanning 70 years, knowing where to start is the first challenge. Here\'s a tiered reading guide based on your experience level — from first-time investor to seasoned professional.',
    content: `
<p>The question we get most often: "Where should I start?" With 102 letters across 70 years, the honest answer is: it depends on where you are as an investor. Here are three paths, based on experience level.</p>

<h2>Level 1: New to Value Investing</h2>
<p>Start with five letters that establish the conceptual foundation:</p>
<ul>
<li><strong>1977 Berkshire Letter</strong> — Introduces the concept of "moats" and discusses what makes a business durable. Most foundational text in all of Buffett's writing.</li>
<li><strong>1987 Berkshire Letter</strong> — The market crash letter. Short, honest, and demonstrates exactly how Buffett thinks about panic vs. opportunity.</li>
<li><strong>1996 Berkshire Letter</strong> — Discusses the "hundred-year flood" concept and why diversification matters for most investors. Excellent bridge between theory and practice.</li>
<li><strong>2000 Berkshire Letter</strong> — The tech bubble letter. Buffett explains clearly why he didn't participate — and what he missed vs. what he avoided deliberately.</li>
<li><strong>2025 Farewell Letter</strong> — The final letter. Reading this after the earlier ones, you can see how fully his thinking matured while his core principles remained constant.</li>
</ul>
<p>Reading time for these five: approximately 4–5 hours total. Time invested: high. Understanding gained: the framework that underlies every subsequent letter.</p>

<h2>Level 2: Intermediate — Know the Basics</h2>
<p>You understand margin of safety and intrinsic value. Now you want to see how Buffett applied these concepts across different situations:</p>
<ul>
<li><strong>1962–1969 Partnership Letters</strong> — The清算 (liquidation) letters. Watching Buffett close his partnership while explaining his reasoning to Limited Partners is masterclass communication.</li>
<li><strong>1983 Berkshire Letter</strong> — See's Candies and the origin of " Wide Moat." This is the single most-cited letter by serious Buffett scholars.</li>
<li><strong>1992 Berkshire Letter</strong> — "The Superinvestors of Graham-and-Doddsville." Buffett's philosophical defense of value investing — and his famous bet against efficient markets.</li>
<li><strong>2008 Berkshire Letter</strong> — The financial crisis. Buffett was buying. Read what he was thinking.</li>
<li><strong>2019 Berkshire Letter</strong> — The battle between operating earnings vs. acquisition impairments. Buffett's transparency about accounting choices is remarkable.</li>
</ul>

<h2>Level 3: Advanced — Structural Analysis</h2>
<p>You want to understand not just <em>what</em> Buffett thought, but <em>how</em> he evolved:</p>
<ul>
<li>Read the partnership letters chronologically (1956–1970). The evolution from Graham disciple to independent thinker is visible.</li>
<li>Cross-reference letters by topic: search for "intrinsic value" across all letters and read the passages in sequence.</li>
<li>The 1989 and 1990 letters together document the first signs of Buffett's thinking about banking — which would become his largest sector concentration.</li>
<li>Compare the 2011 and 2018 IBM letters: watch a position being built, defended, and exited — all in public.</li>
</ul>

<h2>The One Letter Everyone Skips But Shouldn't</h2>
<p><strong>1999 Berkshire Letter</strong> — Almost no one reads this because it contains Buffett's famous admission that he missed the technology bubble entirely. Most investors find it uncomfortable. It's actually the most honest letter he ever wrote: a public acknowledgment of a significant gap in his circle of competence, made at the peak of that gap's cost.</p>
    `,
  },
]

// --------------------------------------------------------
// Helpers
// --------------------------------------------------------

export function getAllPosts(): BlogPost[] {
  return [...blogPosts].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
}

export function getRecentPosts(count: number): BlogPost[] {
  return getAllPosts().slice(0, count)
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug)
}

export function getPostsByTag(tag: string): BlogPost[] {
  return blogPosts.filter((p) => p.tags.includes(tag))
}

export function getFeaturedPost(): BlogPost | undefined {
  return blogPosts.find((p) => p.featured)
}

export function getAllTags(): string[] {
  const tagSet = new Set<string>()
  blogPosts.forEach((p) => p.tags.forEach((t) => tagSet.add(t)))
  return Array.from(tagSet).sort()
}
