/**
 * Generate lightweight search data for Cloudflare Pages Functions
 *
 * Run: npx tsx scripts/generate-search-data.ts
 * This extracts only the fields needed for search from the full data files,
 * avoiding the 1MB+ bundle size of importing data/letters.ts directly.
 */

import { allLetters } from '../data/letters'
import { concepts } from '../data/concepts'
import { companies } from '../data/companies'
import * as fs from 'fs'
import * as path from 'path'

// ── Extract lightweight search fields ──

const lettersData = allLetters.map((l) => ({
  slug: l.slug,
  title: l.title,
  year: l.year,
  summary: l.summary,
  concepts: l.concepts,
  companies: l.companies,
}))

const conceptsData = concepts.map((c) => ({
  slug: c.slug,
  name: c.name,
  definition: c.definition,
}))

const companiesData = companies.map((c) => ({
  slug: c.slug,
  name: c.name,
  industry: c.industry,
}))

// ── Generate TypeScript file ──

const output = `// AUTO-GENERATED by scripts/generate-search-data.ts
// Do NOT edit manually — run \`npx tsx scripts/generate-search-data.ts\` to regenerate.
// Generated at: ${new Date().toISOString()}

export const LETTERS_DATA: Array<{
  slug: string
  title: string
  year: number
  summary: string
  concepts: string[]
  companies: string[]
}> = ${JSON.stringify(lettersData, null, 2)}

export const CONCEPTS_DATA: Array<{
  slug: string
  name: string
  definition: string
}> = ${JSON.stringify(conceptsData, null, 2)}

export const COMPANIES_DATA: Array<{
  slug: string
  name: string
  industry: string
}> = ${JSON.stringify(companiesData, null, 2)}
`

const outPath = path.join(__dirname, '../functions/api/search-data.ts')
fs.writeFileSync(outPath, output)

console.log(`\u2705 Generated functions/api/search-data.ts`)
console.log(`   Letters:    ${lettersData.length}`)
console.log(`   Concepts:   ${conceptsData.length}`)
console.log(`   Companies:  ${companiesData.length}`)
